---
# roles/og/tasks/main.yml

- name: copy gobgpd conf
  template: 
    src: gobgpd.conf.j2
    dest: "/etc/gobgp/gobgpd.conf"

- name: copy gobgpd service file
  copy: 
    src: gobgpd.service
    dest: "/etc/systemd/system"

- name: copy zebra conf
  copy:
    src: zebra.conf
    dest: "/etc/quagga"

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: enable zebra
  systemd:
    name: zebra
    enabled: yes
    state: restarted

- name: start gobgp
  systemd:
    name: gobgpd
    enabled: yes
    state: started

- name: add default gateway for routes to client subnet
  become: yes
  become_user: root
  shell: ip route add {{ bgp_fabric.anycast_range }} via {{ bgp_fabric.neighbor.address }} dev enp0s8

- name: add default gateway for routes to spine devices
  become: yes
  become_user: root
  shell: ip route add 10.0.255.0/24 via {{ bgp_fabric.neighbor.address }} dev enp0s8

