---
# host_vars/bgp-1.yml

bgp_fabric:
  asn: "{{ dcs.dc1.asn }}" # matches spine-1
  router_id: "{{ dcs.dc1.bgp_network_prefix }}.{{ bgp_host }}"
  neighbor:
    id: "'{{ spine_network_prefix }}.{{ dcs.dc1.spine_host }}'"  # spine-1 ip address of connected port
           
    remote_as: "{{ dcs.dc1.asn }}"  # matches spine-1
    local_ip: "{{ dcs.dc1.bgp_network_prefix }}.{{ dcs.dc1.spine_host }}"
  anycast_ranges: 
    - range: "{{ app_anycast }}" # CIDR used for anycast IP
      med: "{{ dcs.dc1.med }}"
    - range: "{{ dcs.dc1.anycast }}"
      med: "{{ dcs.dc1.med }}"

bgp_subnets:
  - "{{ dcs.dc2.bgp_network }}"

bgp_interfaces: # see comments in Vagrantfile, regarding naming of interfaces for private network interfaces
  - enp0s8
  - enp0s9

