---
# host_vars/bgp-2.yml

bgp_fabric:
  asn: "{{ dcs.dc2.asn }}" # matches spine-2
  router_id: "{{ dcs.dc2.bgp_network_prefix }}.{{ bgp_host }}"
  neighbor:
    id: "{{ spine_network_prefix }}.{{ dcs.dc2.spine_host }}" # spine-2 ip address of connected port
    remote_as: "{{ dcs.dc2.asn }}"  # matches spine-2
    local_ip: "{{ dcs.dc2.bgp_network_prefix }}.{{ dcs.dc2.spine_host }}"
  anycast_ranges:
    - range: "{{ app_anycast }}" # CIDR used for anycast IP
      med: "{{ dcs.dc2.med }}"
    - range: "{{ dcs.dc2.anycast }}"
      med: "{{ dcs.dc2.med }}"
  anycast_nexthop: "{{ dcs.dc1.og_network_prefix }}.{{ og_host }}"

bgp_subnets:
  - "{{ dcs.dc1.bgp_network }}"

bgp_interfaces: # see comments in Vagrantfile, regarding naming of interfaces for private network interfaces
  - enp0s8
  - enp0s9

