---
# host_vars/cli-2.yml

anycast_subnets:
  - "{{ app_anycast }}"
  - "{{ dcs.dc1.anycast }}"
  - "{{ dcs.dc2.anycast }}"

anycast_default_gateway: "{{ dcs.dc2.client_network_prefix }}.{{ dcs.dc2.spine_host }}" # spine-1 client network address

