---

loopback: 10.255.0.1/32

bgp_fabric:
  asn: 65000
  router_id: 10.255.0.1
  neighbor:
    - {address: 10.0.255.2, remote_as: 65001}
    - {address: 10.0.255.10, remote_as: 65002}
    - {address: 10.0.255.18, remote_as: 65003}
    - {address: 10.0.255.26, remote_as: 65004}
  networks:
    - 10.255.0.1/32
    - 10.0.255.0/30
    - 10.0.255.8/30
    - 10.0.255.16/30
    - 10.0.255.24/30
    - 10.0.251.0/24

interfaces:
  Ethernet1:
    alias: downlink-og-1
    port_state: no switchport
    address: 10.0.255.25/30
  Ethernet2:
    alias: uplink-cli-1
    port_state: no switchport
    address: 10.0.251.2/24
