---

loopback: 10.255.0.2/32

bgp_fabric:
  asn: 65002
  router_id: 10.255.0.2
  neighbor:
    - {address: 10.0.252.3, remote_as: 65003}
  networks:
    - 10.255.0.2/32
    - 10.0.151.0/24
    - 10.0.252.0/24
    - 10.0.153.0/24

interfaces:
  Ethernet1:
    alias: uplink-cli-1
    port_state: no switchport
    address: 10.0.151.2/24
  Ethernet2:
    alias: cross-spine-2
    port_state: no switchport
    address: 10.0.252.2/24
  Ethernet3:
    alias: downlink-bgp-1
    port_state: no switchport
    address: 10.0.153.21/24
  Ethernet4:
    alias: downlink-og-1
    port_state: no switchport
    address: 10.0.153.22/24
  Ethernet5:
    alias: downlink-app-1
    port_state: no switchport
    address: 10.0.153.23/24
