---

loopback: 10.255.0.3/32

bgp_fabric:
  asn: 65003
  router_id: 10.255.0.3
  neighbor:
    - {address: 10.0.252.2, remote_as: 65002}
  networks:
    - 10.255.0.3/32
    - 10.0.251.0/24
    - 10.0.252.0/24
    - 10.0.253.0/24

interfaces:
  Ethernet1:
    alias: uplink-cli-2
    port_state: no switchport
    address: 10.0.251.2/24
  Ethernet2:
    alias: cross-spine-1
    port_state: no switchport
    address: 10.0.252.3/24
  Ethernet3:
    alias: downlink-bgp-2
    port_state: no switchport
    address: 10.0.253.21/24
  Ethernet4:
    alias: downlink-og-2
    port_state: no switchport
    address: 10.0.253.22/24
  Ethernet5:
    alias: downlink-app-2
    port_state: no switchport
    address: 10.0.253.23/24

