---
# roles/og/tasks/main.yml

- name: copy gobgpd conf
  template: 
    src: gobgpd.conf.j2
    dest: "/etc/gobgp/gobgpd.conf"

- name: copy gobgpd service file
  copy: 
    src: gobgpd.service
    dest: "/etc/systemd/system"

- name: copy zebra conf
  copy:
    src: zebra.conf
    dest: "/etc/quagga"

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: enable zebra
  systemd:
    name: zebra
    enabled: yes
    state: restarted

- name: start gobgp
  systemd:
    name: gobgpd
    enabled: yes
    state: started

- name: add default gateway for routes to spine attached subnets, except bgp
  become: yes
  become_user: root
  shell: ip route add {{ item }} via {{ bgp_fabric.neighbor.local_ip }} dev enp0s8
  with_items: "{{ spine_subnets }}"
  ignore_errors: yes # if adding existing route it will error out

- name: add default gateway for routes to other bgp subnets
  become: yes
  become_user: root
  shell: ip route add {{ item }} via {{ bgp_fabric.neighbor.local_ip }} dev {{ bgp_interfaces[0] }}
  with_items: "{{ bgp_subnets }}"
  ignore_errors: yes 

- name: advertise routes to anycasted range
  become: yes
  become_user: root
  shell:  gobgp global rib add -a ipv4 {{ item.range }} nexthop {{ bgp_fabric.anycast_nexthop }} med {{ item.med }} 
  with_items: "{{ bgp_fabric.anycast_ranges }}"
 
