---
- hosts: cli
  gather_facts: False
  become: true
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: cli
  become: true
  become_user: root
  vars:
    cli:
      username: vagrant
      password: vagrant

  tasks:

  - name: routing for anycast subnet uses spine as default gateway
    shell: ip route add {{ item }} via {{ subnets_to_reach_default_gateway }} dev {{ cli_interfaces[0] }}
    with_items: "{{ subnets_to_reach }}"
    ignore_errors: yes # adding a route that exists will result in error
