---

- hosts: network

  connection: local
  gather_facts: 'False'

  vars:
    cli:
      username: vagrant
      password: vagrant

  roles:
    - leafgroups
    - hostname
    - interfaces
    - routing
    - ntp

- hosts: og

  connection: local
  gather_facts: False
  vars:
    cli:
      username: vagrant
      password: vagrant

  roles:
    - og
